### ISSUE TITLE
[BUG] Unable to register or login

### ISSUE THREAD

**Issue by KoSukeWork** [w3itch-crafter/w3itch-frontend#62]
**Describe the bug**
After using Wallet Connect to connect, login and get stuck at “You're already started login, if your wallet not responding, please refresh this page.“
If you enter the registration step, you will get the correct address, but you will not be able to create an account. Click "Create account" nothing happens

**Expected behavior**
Correct registration feedback or login feedback

**Desktop (please complete the following information):**
 - OS: Windows11-21H2 (22000.613)
 - Browser: Microsoft Edge 100.0.1185.39

**Comment by w3itch** [comment]
Thank you for your support and bug reports! 😊
We've noticed that the registration and login process is now easily broken，The solution probably goes something like this.
Check if the current address is already registered, if not then direct to register.
Not interrupt the process just because the wallet is already connected to start the registration/login.
If registration/login fails, give correct feedback and revert to a state where you can retry
